#!/bin/sh /etc/rc.common
 
START=95
USE_PROCD=1

start_service() {
        SYNCSCRIPT="/mnt/UDISK/printer_data/config/Filament-Sync-Service/data" 
        procd_open_instance
        procd_set_param command sh ${SYNCSCRIPT}
        procd_set_param respawn  # respawn the service if it exits
        procd_close_instance
}