#!/bin/sh
#
# Filament Sync Service
#

PIDFILE=/var/run/filamentsync.pid

start() {
      echo "Starting Filament-Sync-Service"
      start-stop-daemon --start --quiet --exec /root/Filament-Sync-Service/service/sync.sh k1 \
                          --background --pidfile $PIDFILE --make-pidfile \
}
stop() {
      echo "Stopping Filament-Sync-Service"
      start-stop-daemon -K -q -p $PIDFILE
}
restart() {
      stop
      sleep 1
      start
}

case "$1" in
      start)
            start
            ;;
      stop)
            stop
            ;;
      restart|reload)
            restart
            ;;
      *)
            echo "Usage: $0 {start|stop|restart}"
            exit 1
esac

exit 0